### PR TITLE
Changed Jumpad Block

### PR DESCRIPTION
**Pull request by kanedabeast**
I think we should change the jumpad block only because sometimes people use wool and it's really annoying for them, sometimes half of them are not even superadmins so i have changed the block to glass. Reason 1: Because hardly anyone uses it for a ground mainly for walls.

### CODE REVIEW

**Comment by ReelPattytothewatty** [comment]
Kane, Please make an issue, if it gets accepted, then you can make a Pull Request.
Thanks

**Comment by Wild1145** [comment]
Please create an associated issue, and only resolve one issue per PR. Here you are also adding a TPAS command that is both unnecessary and completely pointless as it mimics the saconfig command setup.

**Comment by DUFCLiam** [comment]
@kanedabeast, Please may you remove the TPaS system please.

**Comment by JeromSar** [comment]
This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Pull request closed without merging**
