### PR TITLE
Auto enable commandspy

### PR DESCRIPTION
**Pull request by MrImmaculate**
While still allowing it to be toggled with the command.

### CODE REVIEW

**Comment by DUFCLiam** [comment]
Agreed it can just see if it was enabled on last login so you do not have to do /cmdspy everytime

**Comment by Wild1145** [comment]
I have suggested this to @JeromSar previously however I believe he wanted to leave it how it was and have it "Opt-In" not "Opt-Out".

I do like the idea however of having it "Opt-Out" because a lot of people (Me especially) forgets to enable command spy when they login, then get problems trying to figure out what happened when... This just makes it easier.

**Comment by PacksGamingHD** [comment]
I vouch for this idea

`test`

**Comment by MrImmaculate** [comment]
This does not enable cmdspy, I am going to close this PR and open a new one that actually does it.

**Comment by JeromSar** [comment]
@MrImmaculate Instead, why not append your changes to this PR to avoid cluttering the repository?

**Comment by JeromSar** [comment]
This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Pull request closed without merging**
