### PR TITLE
Set command output gamerule to false.

### LINKED ISSUE #1018: Disable command feedback gamerule
/playsound is a rather spam-filled command as it is widely used and can be spammed to "clear" the chat, therefor making you scroll. Normally, this isn't a huge problem when its used about one time, but when two or more people use it frequently, it can be rather annoying, especially if a staff member is also doing so.

### PR DESCRIPTION
**Pull request by DUFCLiam**
#1018

### CODE REVIEW

**Comment by JeromSar** [comment]
@DUFCLiam This is the wrong approach. As the [contributing guidelines](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing) (_please read them!_) dictate. The use of `dispatchCommand()` should be avoided at all times. In this case, both Bukkit and TFM have an API for handling gamerules. I suggest you use TFM's API which sets a couple of gamerules by default.

**Comment by LegendIsAwesomes** [comment]
People really need to start reading the contributing guidelines, I decided every time I make a new PR I read the guidelines before opening it.

**Comment by JeromSar** [comment]
@LegendIsAwesomes That's probably a good idea. :)

**Comment by DUFCLiam** [comment]
@JeromSar I did I could not find a way to get around this.

**Comment by LegendIsAwesomes** [comment]
@DUFCLiam Theres multiple ways around this

**Pull request closed without merging**
