### PR TITLE
Add's a cooldown for /report

### PR DESCRIPTION
**Pull request by kobetricee**
Just a small update, It blocks players from spamming /report to admins [Works tested on mc.frostedop.net]

### CODE REVIEW

**Comment by JeromSar** [comment]
Hi. Thanks for contributing. Could you link this PR to an open issue for discussion, as per the contributing guidelines?

**Review by Wild1145 — CHANGES_REQUESTED** [review]
Please address the merge conflicts.

**Comment by kobetricee** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/issues/2049

**Comment by JeromSar** [comment]
Please rebase your commit to the `devel` branch. It is the main development branch.

**Pull request closed without merging**
