### PR TITLE
Update bans.yml

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by RobinGall2910** [comment]
You completely screwed up the format. @DUFCLiam

**Comment by DUFCLiam** [comment]
Wait before you accuse me. Look at this:

`-# Ip: [IP-address / UUID]:[Last login name]:[Expiry unix timestamp (0 = never)][Banned by]:[Reason]`
and look at this:

`- '192.168.1.254:Notch:Prozza:0:IP ban example'`

Therefore the format is different; So I fixed it.

**Comment by RobinGall2910** [comment]
You missed it last time.

**Comment by JeromSar** [comment]
This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Comment by DUFCLiam** [comment]
@JeromSar Well update bans.yml then manually

**Pull request closed without merging**
