### PR TITLE
Fix /premium

### LINKED ISSUE #1850: /prem error
When using the command /prem, it gives an error that it cannot connect to mojangs servers.

### PR DESCRIPTION
**Pull request by notanoperator**
Fixes #1850 
Compiles and Works:
</img>

### CODE REVIEW

**Comment by notanoperator** [comment]
PR: Needs Changes

**Comment by mayokek** [comment]
It doesn't met the contribution guidelines...

**Comment by notanoperator** [comment]
It doesn't need testing, it works.

**Comment by foxcqrn** [comment]
How, really, does this "fix" any "problem"
I don't really see anything wrong with /prem

**Comment by Telesphoreo** [comment]
@FoxIshDaBest the old API server we used no longer works. Thus the code had to be modified to a new server so it validates if a player is premium or not correctly

**Comment by foxcqrn** [comment]
Seems legit

**Comment by Wild1145** [comment]
The related issue has already been resoled in a early commit.

**Pull request closed without merging**
