### PR TITLE
Telnet clan. rank

### PR DESCRIPTION
**Pull request by fionn123**
I believe there should be a telnet clan rank in game like a saconfig setrank (username) telnet_clan_admin or something. As I believe, this would stop a lot of confusion and make it easier, for admin chat, I'd suggest [TCA] and for tag I'd suggest [Telnet-ClanForge] or something else, up to prozza, but what do you think?

### CODE REVIEW

**Comment by robingall2910** [comment]
No, since this is a TF exclusive rank only, it wouldn't happen unless you made this certain rank only for TFM mod on TF and would've not commited/coded the certain rank on this github repository.

btw why the hell did you add commits

**Comment by Wild1145** [comment]
As there is no change in permissions there is no need.

Also, this mod is designed for TF so any additions that are made should focus on TF and no other servers.

**Comment by Wild1145** [comment]
Also, this PR is complete crap... Like complete and utter crap...

**Comment by JeromSar** [comment]
@fionn123 I don't believe you understand how PRs work.

**Pull request closed without merging**
