### PR TITLE
Update /setl description.

### LINKED ISSUE #708: Incorrect /setl discription
I was coding and I came across this line in the code as apposed to another line:

@CommandPermissions(level = AdminLevel.SUPER, source = SourceType.BOTH)
@CommandParameters(description = "Sets everyone's Worldedit block modification limit to 500.", usage = "/<command>")
public class Command_setl extends TFM_Command

 TFM_Util.adminAction(sender.getName(), "Setting everyone's Worldedit block modification limit to 2500.", true);
        for (final Player player : server.getOnlinePlayers())

Read the desctiption and then see what it does.

### PR DESCRIPTION
**Pull request by Adaptified**
Closes #708

### CODE REVIEW

**Comment by JeromSar** [comment]
@Scuph Thanks for contributing, this PR will be merged soon!

**Comment by ImScoop** [comment]
Bump?

**Comment by Wild1145** [comment]
@JeromSar Bumping,

**Comment by JeromSar** [comment]
@ImScoop After some review, you could change the message to say "the default limit" instead of hardcoding a figure?

**Comment by ImScoop** [comment]
Done @JeromSar

**Comment by Wild1145** [comment]
@JeromSar Re-Open?

**Pull request closed without merging**
