### PR TITLE
Update Command_smite.java (Cosmetic Change)

### PR DESCRIPTION
**Pull request by ghost**
This update makes smite messages stand out more in chat and to the smitten player (since even if a reason is specified, the smitten user wont know why they were smitten most of the time). It changed the default red text to a higher contrast/colour (yellow with the colour code §e/&e). This update makes it easier for people to view the reason for their smite and the smitten player theirself since the current colour (red) of smite reasons look dull and don't stand out.

### CODE REVIEW

**Comment by Wild1145** [comment]
Thank you for contributing to the project, could you please amend your opening message to include the issue that this PR resolves. Thank You.

**Comment by ghost** [comment]
Issue made: https://github.com/TotalFreedom/TotalFreedomMod/issues/2010

**Comment by Wild1145** [comment]
Ref #1552

**Review by Wild1145 — APPROVED** [review]
Looks good, testing required.

**Review by Wild1145 — DISMISSED** [review]
You have made changes to a lot of files that have no relevance to the PR its self, including adding dependencies and more.

**Comment by lemonsked** [comment]
@Wild1145, wrong base branch.

**Comment by Wild1145** [comment]
@OxLemonxO Thanks for correcting that.

**Review by Wild1145 — APPROVED** [review]
Happy that this works without issue.

**Comment by JeromSar** [comment]
@uyscutix Thanks for contributing! This PR will be merged soon!

**Pull request merged**
