### PR TITLE
Blocks Command Spam

### PR DESCRIPTION
**Pull request by savnith**
https://github.com/TotalFreedom/TotalFreedomMod/issues/2074

[ + ] Blocks last sent command to be sent again.

### CODE REVIEW

**Review by Wild1145 — APPROVED** [review]
Looks good - Testing will be needed.

**Comment by ncurran02** [comment]
@Wild1145, it can’t be merged as the branch is deleted.

**Comment by Wild1145** [comment]
@Focusvity You can still merge it through the Github interface regardless of the branch state as I recall.

**Comment by Wild1145** [comment]
Closing due to inactivity and the original repo being deleted and further changes would be required to implement.

**Pull request closed without merging**
