### PR TITLE
Add description for /fuckoff

### PR DESCRIPTION
**Pull request by PacksGamingHD**
From issue #813

### CODE REVIEW

**Comment by tylerhyperHD** [comment]
Isn't it supposed to have an on/off argument with it?

**Comment by PacksGamingHD** [comment]
No. I think you just type it

**Comment by OxLemonxO** [comment]
it's /fuckoff <on <range> | off>

**Comment by PacksGamingHD** [comment]
No there's a radius

**Comment by JeromSar** [comment]
@PacksGamingHD I'm afraid @OxLemonxO is right.

**Comment by JeromSar** [comment]
This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Pull request closed without merging**
