### PR TITLE
Highlight OP's commands with a color.

### PR DESCRIPTION
**Pull request by LegendIsAwesomes**
Title says it all.

### CODE REVIEW

**Comment by ScuphGamingUK** [comment]
No, it creates chat spam.

**Comment by LegendIsAwesomes** [comment]
Oops @JeromSar I accidentally closed it. Can you open it.

**Comment by looperXD** [comment]
I think there is  a re-open button next to the comment bottom for you @legendisawesome

**Comment by Wild1145** [comment]
They are grey to stop the messages looking like chat messages...

**Comment by LegendIsAwesomes** [comment]
@Wild1145 Can you not change it to a color light purple instead?

**Comment by Wild1145** [comment]
@LegendIsAwesomes You could, but again, it was set like this so its not distracting...

**Comment by LegendIsAwesomes** [comment]
@Wild1145 I know what you're talking about but i find grey way too hard to look at when searching for a cmd a op did.

**Comment by Wild1145** [comment]
@LegendIsAwesomes That is true... Another colour would be useful, its just finding which one... Is it ChatColor.GREY or ChatColor.DARK_GREY? If its GREY maybe we should try DARK_GREY (As I think it has one of those)

**Comment by Hockeyfan360** [comment]
Bold the text?

**Comment by LegendIsAwesomes** [comment]
@wild1145 DARK GREY would work better if it was implemented, I'll make a commit later.

**Comment by Hockeyfan360** [comment]
I'm going to be brutally honest, this is absolutely useless and would be extremely distracting.

**Comment by JeromSar** [comment]
@LegendIsAwesomes This would only make OP commands harder to read. I don't think we want this, sorry.

**Pull request closed without merging**
