### PR TITLE
Grammar mistake

### PR DESCRIPTION
**Pull request by CrafterSmith12**

### CODE REVIEW

**Comment by Wild1145** [comment]
I may be getting this muddled up with web based languages, but cant the ' 's cause issues with formatting?

**Comment by Obi2** [comment]
I don't think the original message was erroneous - "everyone's" should be correct.
https://english.stackexchange.com/questions/6058/should-i-use-everyones-everyones-or-everyones

**Comment by OutOfYourMind** [comment]
I agree with Obi2, the apostrophe is to show possession, you possess the creative gamemode.

**Comment by JeromSar** [comment]
After some review, @Obi2  turns out to be right, closing.

**Pull request closed without merging**
