### PR TITLE
Made smaller rules command

### PR DESCRIPTION
**Pull request by AlexFreedomMod**
i have made a smaller rules commnad.

### CODE REVIEW

**Comment by AlexFreedomMod** [comment]
I just fixed the spelling mistakes and checked for errors.

**Comment by StevenLawson** [comment]
Please test your code before you submit a pull request. This code is broken.

Brokenness aside, I believe the Essentials version of */rules* or something similar is currently being used. Even if that wasn't the case, this needs to be implemented in a way where it isn't hard coded into the source.

**Comment by Wild1145** [comment]
In all honesty, if we plan to stick with essentials longer term, we are better off just modifying the essentials rules.txt / rules.yml (I cant remember which one) and using that for /rules.

**Comment by AlexFreedomMod** [comment]
I think its yml, @Wild1145 you are right. The /rules on essentials would of been better.

**Comment by xDestroyer217** [comment]
@Wild1145 Its rules.txt c:

**Pull request closed without merging**
