### PR TITLE
TFM Update

### PR DESCRIPTION
**Pull request by marcocorriero**
This TFM update will contain those function

Coded by

Marco
Mafrans
OxlemonxO

- added /adminhelp
- Added Color supporting/filters for adminchat
- implemented smite to say the sender to player smited.
- implemented Whohas to support Clear, it clears the specified item from the player inventory.
- implemented gmsp, you can put other players in GMSP If required eg Helpers, Trusted players etc.
- Tban alias /noob supports and shows reason
- Glist says the reason in public and ip is showed as client-side
- Fixed /dtoggle thanks to oxlemonxo
- updated tag filtering
- colorized SENIOR_CONSOLE as Pink as asked by mashedPotato.
- Colorized Telnet_Console as Dark_green
- added Block to written_book
- lifted Block for Structure_block (not structure_void, those blocks can help building)
- added a FUTIL Filtering for banned colors. (removed due to Text bugs)
@JeromSar

### CODE REVIEW

**Comment by marcocorriero** [comment]
#1813

**Comment by AvalancheYT** [comment]
Incorrect formatting, don't use import static or *, multiple of these updates are not needed.

**Comment by marcocorriero** [comment]
@AvalancheYT i used the original tfmod code, this tfm code on github is outdated, @JeromSar need to update it. 

P.s i decompiled the totalfreedom mark sent to me, and what is not needed?

**Comment by PacksGamingHD** [comment]
Incorrect formatting, you need to use camel case I believe.
Also I think this should be a milestone (aka TFM 5.0.1 since 5.1 is in the works)
Also some of the grammar needs to be fixed, and the formatting is horrid.

**Comment by AvalancheYT** [comment]
@marcocorriero,
List of what is not needed:
  - ```/adminhelp``` as we got ```/report```
  - Supporting chatcolor in adminchat
  - Colorize telnet and senior console, most admins should know which rank you are.
  - Putting others in Spectator, it defeats the purpose of our administration, catching griefers, watching players in adminworld etc.

**Comment by marcocorriero** [comment]
@AvalancheYT /adminhelp is a /report alternative, is not requiring an name IGN. Report always required an IGN

Minding adding some fun in adminchat? let's just make adminchat supporting colors btw

spectator is for admin only. No one can set it.

Ill delete the FUTIL.Filtering. Because futil bugs some text commands as i discovered

@JeromSar

**Comment by AvalancheYT** [comment]
@marcocorriero, ```/adminhelp``` is based off ```/report```
No need to add 'fun' to adminchat
Read my last sentence about Spectator.

**Comment by PacksGamingHD** [comment]
What do you have against having color in the adminchat

**Comment by AvalancheYT** [comment]
Colour in adminchat is just useless.

**Comment by marcocorriero** [comment]
@AvalancheYT if you dont like it, you can talk with the defaut color....

**Comment by JeromSar** [comment]
Thanks for contributing.

While I really appreciate that time and effort you have invested into this. This PR completely ignores the [Contributing Guidelines](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing) (especially the [Pull Request Requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements)). For that reason, I am closing this PR.

Here are some hints to help you to get PRs accepted in TFM:
* Read the contributing guidelines
* Make one unique PR per feature you're adding
* Each feature or change must be backed by a pre-existing _accepted_ issue
* Code should be formatted in Allman Style
* Read the Java Coding conventions (avoid `.*` imports)

As a side-note, the code available on this repository is _the most recent version of the sourcecode_. Other source archives (including those obtained through decompilation, are inaccurate or outdated.

**Pull request closed without merging**
