### PR TITLE
Remove "-s" and "-c" from "/opall"

### PR DESCRIPTION
**Pull request by DUFCLiam**
#948

### CODE REVIEW

**Comment by Adamx120** [comment]
Bad Idea.

**Comment by DUFCLiam** [comment]
How @Adamx120

**Comment by Adamx120** [comment]
We don't use that

**Comment by DUFCLiam** [comment]
Most people use "-c" but people can abuse "-s" and also heard of CreativePvP this is the reason sometimes an admin has done "/opall -c" and the user has not noticed therefore they have been smitten for something the admin technically done.

**Comment by OnlineRepz** [comment]
Duplicate of #912

**Comment by JeromSar** [comment]
@OnlineRepz PRs are never duplicates.

**Comment by JeromSar** [comment]
PR is on hold, associated issue is not accepted.

**Comment by JeromSar** [comment]
Associated issue is closed.

**Pull request closed without merging**
