### PR TITLE
Make /say More Noticeable?

### PR DESCRIPTION
**Pull request by FoxyCodes**
Hey?. I am NoobsAreGod and I tweaked the /say command to make it alittle more noticeable as since it's a lighter color I think it is less noticed, Here is the source code of what I tweaked

https://pastebin.com/yf22ZRUE

### CODE REVIEW

**Comment by ncurran02** [comment]
To be honest, I like it how it is. And also, if you want to raise a suggestion, please put it in the issue section.

**Review by LiamTownsley — CHANGES_REQUESTED** [review]
This does not have an "issue" and the code changed in the PR does not match the description of the PR...

**Review by robingall2910 — CHANGES_REQUESTED** [review]
redo this entire thing like holy crap fam

**Comment by lemonsked** [comment]
This isn’t a proper PR. Closed.

**Pull request closed without merging**
