### PR TITLE
Adds character limit and adds blocking for forbidden words.

### LINKED ISSUE #2105: rainbowtag bypasses character limit
bringing this from http://totalfreedom.boards.net/thread/54292/fix-rainbowtag so they can stop fighting about it

rainbowtag doesn't have a current character limit and there should be one put in place like the normal tag limit.

### PR DESCRIPTION
**Pull request by robingall2910**
This resolves #2105's issue of the character limit bypass.

Let me know if I did something wrong, I don't really do Java.

### CODE REVIEW

**Comment by Wild1145** [comment]
It looks good. We don't officially support the server branch and its currently a complete mess. It does however look like it would resolve the issue but its something one of the TF developers needs to patch into the server build.

**Comment by ghost** [comment]
@robingall2910 

The travis check failed, this means is not compilin

**Comment by lemonsked** [comment]
@marcocorriero the server branch does not compile with the CI Integration as it's missing the .travis.yml file.

**Comment by ghost** [comment]
This is just copying code from another PR. I recommend this be closed and appended to the functionality in @OxLemonxO's PR.

**Comment by robingall2910** [comment]
@Commodore64x this isn't copied code, and this doesn't go into the `devel` branch. This is going to the `server` branch.

**Comment by Wild1145** [comment]
@robingall2910 Currently failing to build... Looks like you're on the wrong branch... :/

**Pull request closed without merging**
