### PR TITLE
Resolves #1644 (#1716)

### LINKED ISSUE #1644: /doom destroys blocks on explosion.
I'm not quite sure if this is a feature or a bug. When using /doom it destroys blocks. The issue with this is it can cause unwanted grief.

### PR DESCRIPTION
**Pull request by FoxIshDaBest**
Fix /doom breaking blocks

### CODE REVIEW

**Comment by ItzLevvie** [comment]
This is already in tfm51 branch

**Comment by FoxIshDaBest** [comment]
Ik I was creating a pr to merge it to tfm50 branch

**Comment by Wild1145** [comment]
@FoxIshDaBest Why do you keep closing this issue?

**Comment by AvalancheYT** [comment]
@Wild1145, it's already merged.

**Comment by FoxIshDaBest** [comment]
^

**Comment by LegendIsAwesomes** [comment]
It is not already merged, it is ready to merge, meaning keep it open or Jerom won't see it, making it not be merged.

**Comment by AvalancheYT** [comment]
@LegendIsAwesomes, #1716 
It was already merged by the time he made this.

**Pull request closed without merging**
