### PR TITLE
Added "Opping all players on TotalFreedom"

### PR DESCRIPTION
**Pull request by AlphaGaming**

### CODE REVIEW

**Comment by DUFCLiam** [comment]
I do not think this should be added.

**Comment by Wild1145** [comment]
Not necessary as TFM is a multi-server plugin. If you are going to make a change it needs an associated issue and I would advise getting the server name from the config instead so as not to cause a shit storm on other servers without a good reason.

**Comment by ValenciaOrange** [comment]
Honestly, I think we should just keep it short like "Opping all players" and not "Opping all players that is playing on the server" or something like that

**Comment by Adamx120** [comment]
I aggre with Wild.

**Comment by JeromSar** [comment]
This PR does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and thus is closed.

**Pull request closed without merging**
