### PR TITLE
Should fix the Owner Tag

### PR DESCRIPTION
**Pull request by SlicedCaek**
People adding Owner gets Senior Tag.

Works on my side

### CODE REVIEW

**Comment by BigDaddyUS** [comment]
A developer is suppose to confirm the issue before you open a pull request I believe.

**Comment by DaBoyTM** [comment]
This suppose to resolved #504

**Comment by BigDaddyUS** [comment]
Ahh.

**Comment by JeromSar** [comment]
@DaBoyTM hello, thank you for contributing. as per the contribution guidelines (which you should probably review), you should test your changes before making a pull request. The changes made in this PR do compile, but don't work. Please update your PR so I can merge it in. :)

**Comment by Wild1145** [comment]
@DaBoyTM The code its self does function as it *should* however you seem to have forgotten how if statements work. This statement would never be reached.

**Comment by JeromSar** [comment]
@Wild1145 The code doesn't work as it should, either.

**Comment by xDestroyer217** [comment]
That code is in the wrong area... If he cant change it, I will.

**Comment by JeromSar** [comment]
@xDestroyer217 It is his PR, if you wish to make a contribution to TFM, please make a PR.

**Comment by xDestroyer217** [comment]
I will if he doesn't though. @JeromSar

**Comment by DaBoyTM** [comment]
Well, this should fix the problem, Its works, i have even tested, if it doesn't work, then this is strange.

**Comment by xDestroyer217** [comment]
Recent commit should work :100:

**Comment by JeromSar** [comment]
@xDestroyer217 It doesn't work. As I said *test* your code.

**Comment by JeromSar** [comment]
Closing for inactivity.

**Pull request closed without merging**
