### PR TITLE
Unused import

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by Wild1145** [comment]
Little nit picky :P Could have tied it in to another PR :P

**Comment by DUFCLiam** [comment]
:P Ik haha

**Comment by DUFCLiam** [comment]
@JeromSar

**Comment by OxLemonxO** [comment]
yeah that import was used for /permban list and was never removed

**Comment by DUFCLiam** [comment]
Jerom @JeromSar

**Comment by RobinGall2910** [comment]
@DUFCLiam it's low priority. It's going to take a bit to pass the PR anyways.

**Comment by DUFCLiam** [comment]
Ik :P

**Comment by JeromSar** [comment]
This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Pull request closed without merging**
