### PR TITLE
Make's the smite command better small update

### PR DESCRIPTION
**Pull request by kobetricee**
It shortens the smite command instead of 3 lines

### CODE REVIEW

**Comment by JeromSar** [comment]
Could you rebase your commit to the `devel` branch? It is the main development branch. :)

**Comment by JeromSar** [comment]
Could you also link this PR to an open issue for discussion purposes?

**Review by Wild1145 — CHANGES_REQUESTED** [review]
Please make the above changes to rebase this PR so a proper code review can take place.

**Comment by Wild1145** [comment]
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

**Pull request closed without merging**
