### PR TITLE
#1922 fixed (opall -c changing admins gamemodes)

### PR DESCRIPTION
**Pull request by ghost**
Fixes issue #1922 hope this helps :)

### CODE REVIEW

**Comment by lemonsked** [comment]
Merge both of those if statements together?

**Comment by ghost** [comment]
What?

**Comment by mayokek** [comment]
@Commodore64x, Lemon means like instead of using
```java
if (statement)
{
    if (anotherstatement)
    {
    }
}
```
Do
```java
if (statement && anotherstatement)
{
}
```

**Comment by ghost** [comment]
Ok, will fix :P

**Review by Wild1145 — COMMENTED** [review]
Looks good, needs testing.

**Comment by Wild1145** [comment]
Due to the original repo having been destroyed, I am closing this PR down as a result.

**Pull request closed without merging**
