### PR TITLE
Block Replacenear

### PR DESCRIPTION
**Pull request by SlicedCaek**

### CODE REVIEW

**Comment by SlicedCaek** [comment]
@JeromSar, I have tested it on my LAN Server. Worked!

**Comment by WickedGamingUK** [comment]
I'm against this idea. Takes away players freedom. Instead, a limit needs to be introduced so the server doesn't crash because of it.

**Comment by Scuph** [comment]
@WickedGamingUK I agree.

**Comment by AlexFreedomMod** [comment]
@WickedGamingUK Agreeded.

**Comment by OxLemonxO** [comment]
I  used to use removenear when I was an op.
I also think that a limit should be there instead of just blocking it.

**Comment by Wild1145** [comment]
I think it should be blocked, there is no valid reason to use it other than destroying other player builds... I can now easily go to another players build, run a remove near command and no trace I did it...

**Comment by Scuph** [comment]
@Wild1145 it can easily be used for roleplay where in some occasion a certain block type might need to change instantly.

**Comment by SlicedCaek** [comment]
I am on @Wild1145  side... Doesn't matter what limit you got... you can still remove a building (Spawn etc) and escape with it (No trace)

**Comment by WickedGamingUK** [comment]
So while we're at it should we block WorldEdit completely for the same reason? No, that's a stupid idea, exactly the same as blocking this command.

**Comment by Wild1145** [comment]
@WickedGamingUK The difference between blocking worldedit completely and this, is that this has no non-vicious uses that I can think of, whereas a lot of the other worldedit commands have valid useful parts to them, this just removes anything nearby without leaving a trace, even limits wouldnt help here.

**Comment by JeromSar** [comment]
@WickedGamingUK @Wild1145 @Scuph @OxLemonxO @AlexFreedomMod After careful consideration I think we don't want this command blocked. Although it may be used to grief, it's also a vital component of WorldEdit, and blocking it would thus impose more restrictions on whatever's left of the freedom on TF.

We can however modify WorldEdit-TF so that this command follows the regular limits WorldEdit has set . This should reduce the amount of crashing of TF.

@SlicedCaek All in all, thanks for contributing, but I don't think this addition is right for TFM.

**Pull request closed without merging**
