### PR TITLE
Reduce spam of /op

### LINKED ISSUE #538: /op {player name}
I have a good idea, if someone try to op someone that is already opped, it will say This Person/Player is already opped, this might be a good idea to reduce some spam of opping

### PR DESCRIPTION
**Pull request by LegendIsAwesomes**
I had to make a new PR since i accidentally deleted my fork on my other (@JeromSar told me to make a new PR)

Resolves #538

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
@JeromSar this is the one that was going to be merged on my last PR. The playerMsg had to be changed which i did, Tested and it works.

**Comment by JeromSar** [comment]
@LegendIsAwesomes Thank you for contributing. This PR will be merged soon. :)

**Comment by WarrioR151** [comment]
I cant use commands with : 

Like /i diamond_sword {ench:BlahBlahBlah

**Comment by JeromSar** [comment]
@WarrioR151 This is no place to post the problems you're experiencing. Post on the forums.

**Comment by DUFCLiam** [comment]
What was the reason of closure? @JeromSar

**Comment by Wild1145** [comment]
@JeromSar Re-Open?

**Comment by LegendIsAwesomes** [comment]
@JeromSar

**Comment by JeromSar** [comment]
Cannot be reopened.

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes Repo was deleted.

**Comment by LegendIsAwesomes** [comment]
I'll recreate this.

**Comment by DUFCLiam** [comment]
Thank you :) 

I left it for you to do :P

**Pull request closed without merging**
