### PR TITLE
Update superadmin.yml

### PR DESCRIPTION
**Pull request by TheGamingSprite**
I Added The Rank Clan admin and it can been changed in config

### CODE REVIEW

**Comment by DUFCLiam** [comment]
Denied

`PRs must not solely be grammar fixes, config-edits, single-line changes or message rephrasing edits. Small edits such as these take very little effort to make and a lot more effort to review and integrate into the codebase.` 

`PRs must only address issues which are marked as "accepted".`

`PRs must be compiled and tested before they are submitted. If your PR does not function or has clearly not been tested, it may be closed without notice.`

**Comment by LegendIsAwesomes** [comment]
@DUFCLiam you can't deny this.

**Comment by JeromSar** [comment]
@DUFCLiam You cannot deny/close PRs, sorry.

This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Comment by TheGamingSprite** [comment]
:(

**Pull request closed without merging**
