### PR TITLE
Verified rank.

### PR DESCRIPTION
**Pull request by LegendIsAwesomes**
https://github.com/TotalFreedom/TotalFreedomMod/issues/654 I couldn't find any code that solved this issue so i made this. If it was already solved sorry. You can close this if so.

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
Please give me more time to fix this @JeromSar , It doesn't work. Im looking for the issue, Its probably in plain daylight though xD.

**Comment by OxLemonxO** [comment]
You should probably change AdminLevel.SENIOR to AdminLevel.SUPER
As telnets+ can super them.

**Comment by LegendIsAwesomes** [comment]
@oxlemonxo will do when I find why it doesn't work.

**Comment by xDestroyer217** [comment]
Tbh, I don't find this useful if it only adds a 'Verified' tag.

**Comment by Adaptified** [comment]
@xDestroyer217 But the issue was accepted, so.

**Comment by Wild1145** [comment]
If this code never worked, please close this PR, fix your code and open a new PR. You should never have opened the PR if the code was never functional and or tested.

**Pull request closed without merging**
