### PR TITLE
Added , alias /aw

### PR DESCRIPTION
**Pull request by Superior-tL**
Added a update to /adminworld Easyer to access with /aw

### CODE REVIEW

**Comment by Adaptified** [comment]
Issues with this pull request:
- Lack of associated and accepted issue
- One line commit (against contributing guidelines)

Please read the guidelines if you want to contribute to totalfreedommod! :)

**Comment by Superior-tL** [comment]
There where a lot of vouches on the suggestion so I just wanted to add this quick fix.

**Comment by Adaptified** [comment]
It needs to be accepted, if you read the guidelines you would know that.

**Comment by Wild1145** [comment]
This does not follow the contributing guidelines, or the aims of the project. We removed Aliases for a reason.

**Comment by JeromSar** [comment]
Thanks for contributing!

This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements), and because of that, I cannot accept this issue.

**Pull request closed without merging**
