### PR TITLE
Resolves issue #287 - Prevents Creative pvping

### PR DESCRIPTION
**Pull request by AvalancheYT**
Tested on LAN server, worked.

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
The copying and pasting is deal, try to avoid nested if statements.

**Comment by AvalancheYT** [comment]
@LegendIsAwesomes, what are you talking about? I did this by my own.

**Comment by LegendIsAwesomes** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/pull/824

My PR my code. Obviously copied.

**Comment by JeromSar** [comment]
Sure seems like it. Don't violate copyright in the future.

**Pull request closed without merging**
