### PR TITLE
A good Update to TFM!

### PR DESCRIPTION
**Pull request by AlphaGaming**
Updating the Server: to TotalFreedom:

### CODE REVIEW

**Comment by PacksGamingHD** [comment]
its fine the way it is

**Comment by Adamx120** [comment]
Unnecesarry

**Comment by OnlineRepz** [comment]
How that even a good update... Stop making PRs without issues (accepted)

**Comment by JeromSar** [comment]
No thank you.

**Comment by Wild1145** [comment]
It would however be good to change it to dynamically update based on the config value defined here: https://github.com/TotalFreedom/TotalFreedomMod/blob/master/src/config.yml#L9

**Comment by JeromSar** [comment]
@Wild1145 No I think this should stay as "Server" since that is the Bukkit/Minecraft default.

**Comment by Wild1145** [comment]
@JeromSar Eh, I think either works. If it is going to be changed then I dont think we need it to be something static like "TotalFreedom" though, thus why I suggested the dynamic update.

**Pull request closed without merging**
