### PR TITLE
BananaFreedomMod

### PR DESCRIPTION
**Pull request by LucazDaKing**

### CODE REVIEW

**Comment by AlexFreedomMod** [comment]
I don't think this should be on totalfreedomod.

**Comment by Adaptified** [comment]
And isnt allowed

**Comment by Wild1145** [comment]
Dafuk

**Comment by ValenciaOrange** [comment]
Lol banana lol

**Comment by LegendIsAwesomes** [comment]
Im pretty sure they broke the licence @JeromSar , They removed you from superadmin.yml. Isn't that breaking the licence.

**Comment by PacksGamingHD** [comment]
lolwhat? i don't know how pull request works.

How the fuck did it end up here O.o

**Comment by JeromSar** [comment]
@LucazDaKing Eh, no.

**Pull request closed without merging**
