### PR TITLE
typo in config.yml

### PR DESCRIPTION
**Pull request by Telesphoreo**
Just a typo i found

### CODE REVIEW

**Comment by PacksGamingHD** [comment]
also issue 9/11 lol

**Comment by xItsNickHD** [comment]
Great find :)

**Comment by Wild1145** [comment]
Good catch.

**Comment by FoxIshDaBest** [comment]
I noticed that a while ago xP

**Comment by OxLemonxO** [comment]
@PacksGamingHD

**Comment by PacksGamingHD** [comment]
What is needs cla?

**Comment by JeromSar** [comment]
@PacksGamingHD See the check on this PR, click "details".:)

**Comment by PacksGamingHD** [comment]
Done

**Comment by DUFCLiam** [comment]
@JeromSar `PRs must not solely be grammar fixes, config-edits, single-line changes or message rephrasing edits. Small edits such as these take very little effort to make and a lot more effort to review and integrate into the codebase.`

**Comment by JeromSar** [comment]
@DUFCLiam This PR was introduced before that policy, so it's okay. :)

**Comment by DUFCLiam** [comment]
Ahh, I never noticed :)

**Comment by DUFCLiam** [comment]
The date that was introduced in was `December 28, 2015` so this PR is valid.

**Comment by Adaptified** [comment]
If it is something useful, single line commits should be accepted. I heard it's hard to merge them yet I have done that myself, and it shows nothing of difficulty.

**Comment by JeromSar** [comment]
@Adaptified I doubt you have any idea of how exactly such a merge works in practice. Essentially, it would be much easier if I were to make the change myself. Either way, I'm not here to debate our PR process. If you wish to contribute, PRs must show at least a little effort.

**Comment by Adaptified** [comment]
@JeromSar Just by contributing, you put in effort. I understand you might want to include this kind of stuff into commits with other changes but, ehh, it's your repo.

**Review by Wild1145 — APPROVED** [review]
Changes are ready to merge.

**Comment by JeromSar** [comment]
Merged in https://github.com/TotalFreedom/TotalFreedomMod/commit/475b299e37988161b2c0a4fe650d1a6a2fa7685d

**Pull request closed without merging**
