### PR TITLE
Undo rollback when unbanned

### LINKED ISSUE #835: Undo a Rollback if unbanned
I always have the problem if I biaccidently ban the wrong person where all their work goes away and I think that it should revert the rollback if unbanned within two minutes of the ban. This will aviod losing someones hard work if they get banned biaccidently.

### PR DESCRIPTION
**Pull request by LegendIsAwesomes**
Resolves #835

### CODE REVIEW

**Comment by RobinGall2910** [comment]
It's the same as #838.

**Comment by LegendIsAwesomes** [comment]
@RobinGall2910 didn't see that, seems OxLemonxO has abandomed/gone inactive on that PR.

**Comment by RobinGall2910** [comment]
@LegendIsAwesomes but it's been fixed. Why should he go back on that PR?

**Comment by LegendIsAwesomes** [comment]
Where I don't see the commit that fixes it?

**Comment by LegendIsAwesomes** [comment]
Oh i'm stupid, Im gonna leave this up to @JeromSar for him to chose.

**Comment by LegendIsAwesomes** [comment]
Needs unlocking

**Comment by JeromSar** [comment]
This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Pull request closed without merging**
