### PR TITLE
Ban IPs when using /tban

### PR DESCRIPTION
**Pull request by xDestroyer217**
This may work, it may need to be tested.

Goes for #499

### CODE REVIEW

**Comment by JeromSar** [comment]
@xDestroyer217 Hey xDestroyer, thanks for contributing. To get this PR merged, please do the following:
* Test your changes
* Format your changes like the rest of the file is.
* Remove unnecessary comments.

Thanks again, push to this branch to update this PR. :)

**Comment by Wild1145** [comment]
@JeromSar I dont see anything wrong with the comment, it just makes it clear what the part of the code is doing. If anything more of the code should contain comments to make it easier for other developers.

**Comment by xDestroyer217** [comment]
Works in @looperxd's fork of TFM, I tested it, it's a success. :palm_tree:

**Comment by xDestroyer217** [comment]
Sorry about the extra commits, I had some problems.

**Comment by JeromSar** [comment]
@Wild1145 True but it doesn't make sense to have a commit just for IP-banning and not for UUID banning. That's fixed now.

@xDestroyer217 Thanks, all looks good now. I'll merge this PR as soon as I get a chance. :)

**Comment by JeromSar** [comment]
@xDestroyer217 Your changes do not compile. Please *compile and test* your changes before making a PR.

**Comment by xDestroyer217** [comment]
Alright, might been a change that I did on my side.

**Comment by JeromSar** [comment]
@xDestroyer217 When do you think you'll be able to update this?

**Comment by xDestroyer217** [comment]
@JeromSar I got irl stuff to do, I was gonna ask if you can put this on hold.

**Comment by Wild1145** [comment]
Might be better to close it if there are changes needed and let someone else just attempt it if you're going to be busy for a while in all honesty.

**Comment by xDestroyer217** [comment]
@Wild1145, actually, Will do.

**Pull request closed without merging**
