### PR TITLE
Resolves #586

### LINKED ISSUE #586: Command blocker is broken.
I just tested TFM and it appears the command blocker does not work, and no errors are logged in console. Any ideas?

### PR DESCRIPTION
**Pull request by tylerhyperHD**
This reverts to the old TFM command blocker which works in 1.8 to block commands. I tested it on my own server and it ended up working correctly. Your welcome :D

### CODE REVIEW

**Comment by AlexFreedomMod** [comment]
I bet this will work!

**Comment by AlexFreedomMod** [comment]
/\
    /  \
  /     \
 /       \ 
/_____\

**Comment by JeromSar** [comment]
@tylerhyperHD We won't be reverting to old commits. Although it might fix an issue, it removes important functionality.

**Comment by Scuph** [comment]
@JeromSar You have a point, but would you rather have no functionality and have to fix it immediately or have some of it and fix it later on.

**Comment by JeromSar** [comment]
@Scuph This has been fixed now: the fix involved 7 line changes: https://github.com/TotalFreedom/TotalFreedomMod/commit/ea6bfa8387c7c25f2e1a132181663cbf7ea47237

**Pull request closed without merging**
