### PR TITLE
Changed /kicknoob kick message

### PR DESCRIPTION
**Pull request by Scuph**
Just to make sense, lol.

### CODE REVIEW

**Comment by Wild1145** [comment]
Looks like a good chance.

**Comment by AlexFreedomMod** [comment]
Looks good

**Comment by JeromSar** [comment]
Thanks for your contribution, @Scuph. This PR will be merged soon.

**Comment by JeromSar** [comment]
Merged in https://github.com/TotalFreedom/TotalFreedomMod/commit/acc8f3e2b8b76f01ddc1016dbfdc28a9d2300baa Thanks for contributing!

**Pull request closed without merging**
