### PR TITLE
Add /freezenear

### LINKED ISSUE #794: little idea? about freeze...
Why not add /freezenear???

How? /freezenear then freeze near players. [not /fr to general...]

### PR DESCRIPTION
**Pull request by tylerhyperHD**
Creates the command /freezenear

### CODE REVIEW

**Comment by JeromSar** [comment]
@tylerhyperHD Looks good, but needs a few change, see comments.

**Comment by tylerhyperHD** [comment]
I do wanna say to you that this is somewhat of a rewrite of /fuckoff, so I reccomend for you to check that command as well since you clearly don't know how that command was written.

**Comment by tylerhyperHD** [comment]
Some problems were resolved, I need further input from you on what I should do next.

**Comment by tylerhyperHD** [comment]
bump*

**Comment by tylerhyperHD** [comment]
@JeromSar

**Comment by Wild1145** [comment]
@JeromSar Re-Open/

**Comment by DUFCLiam** [comment]
Should be closed due to the release of 5.0; @JeromSar 
And CLA will likely never be signed.

**Pull request closed without merging**
