### PR TITLE
Changing the color of Console

### PR DESCRIPTION
**Pull request by Scuph**
I thought since it was the same color as dev and in adminchat caused a little confusion.

### CODE REVIEW

**Comment by AlexFreedomMod** [comment]
Hmm that would look a bit weird but i guess it will help with that.

**Comment by ImALuckyGuy** [comment]
What is with you and colors? Why do you want them changed so badly?

**Comment by Scuph** [comment]
@ImALuckyGuy

1. Idfk

2. Console was the same as dev, and it was confusing for me.

**Comment by DaBoyTM** [comment]
Yeah nah! I don't think so, way confusing for me if you change the color, purple is fine for me

**Comment by JeromSar** [comment]
To be really honest with you, i don't think this is a necessary change. Please check open PRs with the tag "Issue: Accepted" for possible contributions which will be accepted. Saves you and me a bunch of time. :)

**Pull request closed without merging**
