### PR TITLE
Added name on ban Fixes #350

### LINKED ISSUE #350: Include who banned the players
Something I noticed is that it doesnt include who banned you unless you are /tempban 'd. This seems like a large flaw in the way the server works as one of the appeal points is asking who banned you. 

I suggest adding something like DarthCraft does where its as follows:

You have been banned
Reason: Being a idiot
Banned By: Wild1145

That way it is useful when appealing bans, and means you dont have to put your name in the reasons.

### PR DESCRIPTION
**Pull request by buildcarter8**
* Now figuring out who banned you is simple
* Dont have to put names in reasons
* Added names also when the person bans them such as "buildcarter8 - Banning: Notch, IP: 1.1.1.1"
when they get banned shows up GTFO Banned by: Buildcarter8 and with reasons GTFO Banned by: Buildcarter8 reason: grief

### CODE REVIEW

**Comment by buildcarter8** [comment]
Done @JeromSar

**Comment by JeromSar** [comment]
@buildcarter8 Done? Done!? You made a few changes and tested nothing!

**Comment by Wild1145** [comment]
@buildcarter8 @JeromSar Bumping This issue.

**Comment by JeromSar** [comment]
@buildcarter8 I'll close this as inactivity if you have no further intention of updating it. :)

**Comment by buildcarter8** [comment]
@JeromSar Yeah go ahead i dont even have the fork anymore

**Pull request closed without merging**
