### PR TITLE
Adds worldedit into rollback

### PR DESCRIPTION
**Pull request by ImScoop**
Rollback now supports worldedit.

### CODE REVIEW

**Comment by Adaptified** [comment]
In order for this to work, a redo method must be implemented into the worldedit bridge.

**Comment by JeromSar** [comment]
@Adaptified Looks like a good idea, but there's a couple of things that need changing:
* Implement the `redo` method in TFM_WorldEditBridge
* Remove the call to `undo` in `Command_gtfo`.
* Test this code.

**Comment by Adaptified** [comment]
@JeromSar The redo method I can do, the undo call in gtfo should only work if the player hasn't been rolled back any time near the ban. I can implement this system, give me 5 days.

**Comment by Adaptified** [comment]
Updated @JeromSar

**Comment by ValenciaOrange** [comment]
Bump?

**Comment by Wild1145** [comment]
Formatting is a bit doo-hicky.

**Comment by JeromSar** [comment]
@ImScoop As per the contributing guidelines, using `Bukkit.dispatchCommand()` not permitted.

**Pull request closed without merging**
