### PR TITLE
Limit "/deopall" to senior

### PR DESCRIPTION
**Pull request by DUFCLiam**
#951

### CODE REVIEW

**Comment by Adamx120** [comment]
Unnecessarry, we are don't using it, and admins are very trusted in TotalFreedomMod so don't need to limit opall -s and deopall to senior

**Comment by DUFCLiam** [comment]
Thanks for your view on this

**Comment by JeromSar** [comment]
@DUFCLiam This PR is on hold. Associated issue is not accepted.

**Comment by Wild1145** [comment]
@JeromSar Update status - Original issue was rejected.

**Pull request closed without merging**
