### PR TITLE
IP update for frontdoor

### PR DESCRIPTION
**Pull request by TheWadeSmith**

### CODE REVIEW

**Review by JeromSar — APPROVED** [review]

**Comment by JeromSar** [comment]
Thanks for contributing. Your PR will be merged soon. :)

**Comment by ghost** [comment]
This isn't needed? tf.sauc.in works fine.

**Comment by mayokek** [comment]
I believe the old up directs to the old server.

**Comment by Wild1145** [comment]
Play.totalfreedom.me is however the "Main" IP as it were, and the one we can guarantee will always be up to date in real time.

**Review by Wild1145 — APPROVED** [review]

**Comment by script-head** [comment]
The FrontDoor actually doesn't even work anymore. http://frontdoor.pravian.net:1337 the DNS address doesn't resolve.

**Comment by Wild1145** [comment]
That'd be one for @JeromSar

**Pull request merged**
