### PR TITLE
Resolves #1776

### LINKED ISSUE #1776: smite implement
smite need to say who smites the player.

Ex, prozza already coded Smite reasons, but the smite will stay anonymous,

IF a rcon breaches?
If a telnet go to rogue?

Smite need to say in reason

The admin smites it.

I can help.

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by AvalancheYT** [comment]
This PR does not meet the contributing guidelines.

**Comment by OxLemonxO** [comment]
This PR does not compile. CommandSender has a getName() method, not a getname() method. Line 56.

**Comment by DUFCLiam** [comment]
I coded that in school sorry

**Comment by marcocorriero** [comment]
Duplicate of #1825

**Comment by AvalancheYT** [comment]
@marcocorriero, the PR cannot be duplicated.

**Pull request closed without merging**
