### PR TITLE
Added Cow and Oliver's ranks

### PR DESCRIPTION
**Pull request by AlphaGaming**

### CODE REVIEW

**Comment by xItsNickHD** [comment]
@AlphaGaming, I think you should not make it 'admin' but instead Executive or Moderator based on http://totalfreedom.boards.net/thread/27763/executive-senior-roster-16-oct

**Comment by OnlineRepz** [comment]
Executive is part of Senior. (Admin on forum, senior in-game)

**Comment by LegendIsAwesomes** [comment]
@AlphaGaming these ranks that CowGoMooo12 and OliverDatGuy possess is just a forum rank, they're still senior in game, no need for them to have a separate ingame rank.

**Comment by JeromSar** [comment]
This PR does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and thus is closed.

**Pull request closed without merging**
