### PR TITLE
Created Command_rules.java with all rules from totalfreedom boards

### PR DESCRIPTION
**Pull request by looperXD**
Sometimes player wanted to view the rules but they have access to make a account on forum., But /rules give them a shorten verison of what is on forum. When a new player join they could just do /rules and quickly view all the rules and things they need to know.

Created Command_rules that has rules copied from
http://totalfreedom.boards.net/thread/21065/server-conduct-policy-players-admins

### CODE REVIEW

**Comment by xDestroyer217** [comment]
Or, we can just add the rules to the existing essentials command '/rules'.

**Comment by Wild1145** [comment]
An issue specific to this PR should be opened prior to the PR its self and you should say that it is resolving #XYZ in the commit message.

You also will find that this will spam the chat, and may well (Unlikely) not even display all of it. I also remember this linking to another issue where multiple sub-commands would be config defined, but I cant seem to find the issue number.

**Comment by JeromSar** [comment]
@Wild1145 is right, @looperXD

**Comment by Wild1145** [comment]
@looperXD Are you planning to update this?

**Comment by JeromSar** [comment]
@looperXD Closing for inactivity soon. Are you going to update this?

**Comment by JeromSar** [comment]
I believe Essentials' /rules command is better fitted here.

**Pull request closed without merging**
