### PR TITLE
Create Command_tagclean

### PR DESCRIPTION
**Pull request by DUFCLiam**
https://github.com/TotalFreedom/TotalFreedomMod/issues/725

### CODE REVIEW

**Comment by OnlineRepz** [comment]
Can you not code-copy another command and also you forgot to add .java extension...

**Comment by JeromSar** [comment]
@DUFCLiam Next to the fact that this contribution doesn't function _at all_, this PR is on hold. The associated issue is not accepted.

**Comment by DUFCLiam** [comment]
Well, It gives them an idea then

**Comment by Wild1145** [comment]
@JeromSar Re-open

**Pull request closed without merging**
