### PR TITLE
Toggling chat

### PR DESCRIPTION
**Pull request by CrafterSmith12**
Toggle's the chat for the user.

### CODE REVIEW

**Comment by Chaosiity** [comment]
What issue does this solve exactly?

**Comment by JeromSar** [comment]
There are a lot of things wrong with this PR:
* This PR does not have an associated issue.
* The code in this PR has the potential to hang the server.
* There are formatting errors within this PR.
* The code in this PR does not function.
* The code in this PR does not compile.

**Comment by CrafterSmith12** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/pull/905

I meant to commit this https://github.com/TotalFreedom/TotalFreedomMod/pull/905 - I guess I messed up :/

**Comment by DUFCLiam** [comment]
Should be closed due to the release of 5.0

**Comment by Wild1145** [comment]
Thank you for your contribution. Sadly we have decided to close this issue as there has been no recent activity to this pull request. If you wish to continue working on this PR please re-open the issue and ensure that all requested changes are made.

**Pull request closed without merging**
