### PR TITLE
Use correct carrot item

### LINKED ISSUE #684: Lazer (TNT)  Gun not working.
When you hold a carrot (item 141) in your hand, and toggle explosives on, it is supposed to shoot tnt (if you are a senior). After feeling the need to blow my build up, I tried it out. It did not work.

The reason of this is because 141 is a texture, not an actual item that can be eaten, crafted, or used in any way. The item should be moved to item 391 if you want it to stay a carrot.

http://minecraft-ids.grahamedgecombe.com/

### PR DESCRIPTION
**Pull request by ValenciaOrange**
Solve the problem where you can't blowup things with a carrot.
Tiny Fix

### CODE REVIEW

**Comment by JeromSar** [comment]
@looperXD Have you tested this?

**Comment by looperXD** [comment]
@JeromSar  Tested on my server, Works 100%
In Order to work:
1.After You Senior-ed yourself you need to relog.
2.You need to toggle explosives to on,

**Comment by JeromSar** [comment]
@looperXD Thanks for contributing, this PR will be merged soon!

**Comment by Wild1145** [comment]
@JeromSar Re-Open?

**Pull request closed without merging**
