### PR TITLE
Blocks Wildcard, smite, orbit, and glist

### PR DESCRIPTION
**Pull request by kobetricee**
Harmful commands to do in wildcard, added to blocked_commands.

### CODE REVIEW

**Comment by JeromSar** [comment]
Hi! Thanks for contributing. Could you link this PR to an open issue for discussion, as per the contributing guidelines?

**Comment by kobetricee** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/issues/2050

**Comment by JeromSar** [comment]
Also will need to be rebased to the `devel` branch.

**Review by Wild1145 — CHANGES_REQUESTED** [review]
Needs to be rebased with the devel branch before we can review / merge properly.

**Comment by Wild1145** [comment]
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

**Pull request closed without merging**
