### PR TITLE
Added clarification announcements

### LINKED ISSUE #516: Announcements lack variety
Hi there, announcements are boring and lack variety.  I feel it would be best to add more rule expansion and some more excitement into the announcements.

### PR DESCRIPTION
**Pull request by zD12**
Isn't exactly much to say, it's just some basic explanations and it isn't as annoying with the same three reminders.  Isn't exactly too much knowledge, but just the basics.

Should resolve #516

### CODE REVIEW

**Comment by Wild1145** [comment]
Technically an issue should have been opened before the PR, however to be honest its minor changes, I dont think @JeromSar will mind too much.

**Comment by zD12** [comment]
@Wild1145, I thought because I wasn't modifing any source code I wasn't required to submit an issue.  Nevertheless, I will.

**Comment by Wild1145** [comment]
@zD12 From my understanding, any changes to the project should have a linked issue for the discussion.

**Comment by zD12** [comment]
@Wild1145, thank you for misunderstanding.  That minor issues has since been resolved.

**Comment by JeromSar** [comment]
@zD12 Thanks for your contributions. Mind adding some more announcements? The following might be handy:
- For a list of online superadmins, do /list -a
- See http://totalfreedom.me for information on how to save your creations.
- Online famous players are usually fake. This is an offline-mode server.

Think if you can think of any more.

Thanks,
Jerom

**Comment by Wild1145** [comment]
@JeromSar Don't think need review is the right tag. Needs change sounds more apropriate here

**Comment by zD12** [comment]
@JeromSar I've included some more announcements

**Comment by JeromSar** [comment]
Merged in https://github.com/TotalFreedom/TotalFreedomMod/commit/a15e39d7dd696e1f61fe3da504272a09657fc5f2
Thanks for contributing! :)

**Pull request closed without merging**
