### PR TITLE
Update Command_adminchat.java

### PR DESCRIPTION
**Pull request by Bluay**
Add color to adminchat but blocks forbidden colors.

### CODE REVIEW

**Comment by notanoperator** [comment]
Vouch

**Comment by DUFCLiam** [comment]
@notanoperator, Please do not vouch as this is a development platform and not the forums. :)

**Comment by notanoperator** [comment]
what are you talking about? ;)

I think this would be a good and creative idea

**Comment by DUFCLiam** [comment]
@notanoperator, Jerome will impale your world when you vouch :P I found out the hard way XD

**Comment by robingall2910** [comment]
I think this shouldn't be touched and move on. Besides, CLA said he didn't even sign it.

**Comment by OxLemonxO** [comment]
@robingall2910 It is signed..

**Comment by ItzLevvie** [comment]
^^ He signed the CLA 5 hours ago

**Comment by Wild1145** [comment]
This does not meet the PR Requirements. Please see the contributing guide on how to open PR's on this repo.

**Comment by robingall2910** [comment]
RIP requirements anyway @ItzLevvie and @OxLemonxO

**Comment by JeromSar** [comment]
Thanks for contributing!

This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements), and because of that, I cannot accept this issue.

**Pull request closed without merging**
