### PR TITLE
Fixed two admins not being able to be admin at the same time

### PR DESCRIPTION
**Pull request by ghost**
Fixes issued #1783 as described above.

### CODE REVIEW

**Comment by mayokek** [comment]
Does it really work?

**Comment by Commodore64x** [comment]
What do you think? lmao.....

**Comment by ghost** [comment]
Yes! Of course it works XD. The problem wasn't that hard really, it was kinda obvious what was causing the problem.

**Comment by Wild1145** [comment]
This just adds a known names field to the superadmin.yml but this field would never be filled.

**Comment by ghost** [comment]
@Wild1145 it works. The field is filled and my fix works.

**Comment by Wild1145** [comment]
@Commodore64x You added them, however there is no other code that actually puts the name there.

**Comment by ghost** [comment]
@Wild1145 there does not need to be...

**Comment by lemonsked** [comment]
@Commodore64x Did you even test this?

**Comment by ghost** [comment]
@OxLemonxO  @Wild1145 I see, this is the crappy version I made ages ago not the newest, lemme update.

**Comment by ghost** [comment]
@OxLemonxO I have not had time to extensively test it but yeah, to fully fix the issue something new may need to happen.

**Comment by ghost** [comment]
I am gonna close this as I think that without a major rewrite this will not be possible. Major bugs have terminated the functionality of the TotalFreedom Admin system and require more thought.

**Pull request closed without merging**
