### PR TITLE
Auto-enable commandspy

### PR DESCRIPTION
**Pull request by Adaptified**
:P
Solves #652

### CODE REVIEW

**Comment by Wild1145** [comment]
This PR does not meet the PR Requirements.

**Comment by Adaptified** [comment]
@Wild1145 Yes it does.

**Comment by Wild1145** [comment]
Nowhere within the commits, title or PR description have you outlined what issue this actually resolves. Ideally this should be as part of a commit so the issue auto-closes.

**Comment by Wild1145** [comment]
This also comes under the whole "1 line change thing", you changed 4 lines... Its a lot more work to merge this than re-create it by @JeromSar

**Comment by Adaptified** [comment]
@Wild1145 Then you guys shouldn't accept issues like this - there is no reason to use a more difficult method to auto enable it, this works fine and is the way. By the way, #652.

**Comment by JeromSar** [comment]
This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements) and therefore is closed.

**Pull request closed without merging**
