### PR TITLE
Resolves #826 - /tagnyan

### LINKED ISSUE #826: /tagnyan admin unblocked
Continued from http://totalfreedom.boards.net/thread/28731/pretend-admin?page=1&scrollTo=317067

### PR DESCRIPTION
**Pull request by AvalancheYT**
Updated for TFM 5.0. This should replace with PR #827.

### CODE REVIEW

**Comment by Adaptified** [comment]
As I said before, contributing to 5.0 should be held back until the branch is updated and even.

**Comment by Wild1145** [comment]
@Adaptified There is nothing wrong with contributing to a development branch.

**Comment by Adaptified** [comment]
@Wild1145 It could conflict with the changes that Jerom is making.

**Comment by Wild1145** [comment]
@Adaptified It could, but you can work around the conflicts, I had to all the time with CJFreedomMod.

**Pull request closed without merging**
