### PR TITLE
Update /warn fixes #1805

### LINKED ISSUE #1805: update /warn
I feel that the current /warn is bland and sometimes can be confusing to operators.
I have had multiple operators ask me why the wording was so weird, and who they were warned by.
If this issue is accepted, I can make a pull request for it.

### PR DESCRIPTION
**Pull request by notanoperator**
Fixes https://github.com/TotalFreedom/TotalFreedomMod/issues/1805
Improves the wording of the command.

### CODE REVIEW

**Comment by notanoperator** [comment]
I compiled it once, found my mistake tested forgot to add something and now I get errors (not command related)

**Review by Wild1145 — COMMENTED** [review]
Looks good. Needs testing.

**Comment by Wild1145** [comment]
This build is currently passing in TravisCI, see https://travis-ci.org/Wild1145/TotalFreedomMod/builds/223644529

**Review by Wild1145 — APPROVED** [review]

**Comment by lemonsked** [comment]
@JeromSar think you meant to merge into `devel`

**Pull request merged**
