### PR TITLE
A small file error needs to be accepted!

### PR DESCRIPTION
**Pull request by Superior-tL**
Fixed the command needs to be accepted because the command makes a lot of errors, needs to be added, @JeromSar  @Wild1145

### CODE REVIEW

**Comment by AvalancheYT** [comment]
It doesn't affect other commands.

**Comment by LegendIsAwesomes** [comment]
Please read the guidelines, as one word changes or small changes can not be accepted, this PR also doing have an issue with the label 'Accepted' therefore again, it can not be accepted.

Contributing Guidelines: https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing

**Comment by Wild1145** [comment]
We couldn't actually have aliases anyway if I recall, we were trying to remove them all anyway. But what he said above.

**Comment by JeromSar** [comment]
This is not the way TFM works with aliases.

**Pull request closed without merging**
