### PR TITLE
Resolve #436 | Block **

### LINKED ISSUE #436: Block **
It is really annoying when people use ** in commands like /msg ** and /heal **

I suggest that you block the **

### PR DESCRIPTION
**Pull request by zD12**
This isn't difficult, simply blocking '**' from any and all commands.

### CODE REVIEW

**Comment by zD12** [comment]
@BigDaddyUS it's kinda wordy and I'd rather not.  It isn't nessarily always a command, for example, '/tell ** <message>' will tell the message to all users.  However, '/eco set * 0' will reset everyone's balance, not send them/everybody a command.  That's why I just said, "'**' is prohibited."

**Comment by JeromSar** [comment]
@zD12 Could you change your code to allow SuperAdmins and above to use **? That'd be nice, thanks!

**Comment by JeromSar** [comment]
@zD12 Additionally, do _all_ of the commands supporting entire-server targets use a double-astrix? Are there any commands that use a single astrix instead and is there any reason why we shouldn't be blocking that instead?

**Comment by Wild1145** [comment]
Would it not make sense to block anything including a singlt * as ** is still just two *'s...

**Comment by zD12** [comment]
@Wild1145 and @JeromSar, I thought about that, but, factoring people use '/me hi*' for fixing typos I decided to block double.

**Comment by Wild1145** [comment]
@zD12 Valid point... Not sure how we could work around that problem...

**Comment by zD12** [comment]
@Wild1145 my concern/question, why would administrators need '**'?  We have '/wildcard ?'

**Comment by Wild1145** [comment]
@zD12 They should not need it, neither should anyone to be fair.

**Comment by JeromSar** [comment]
@zD12 Best to provide admins with everything possible in case the time comes when it *is* needed, not taking chances here. :P

**Comment by Wild1145** [comment]
@JeromSar I think the point is, admins do not and should not *need* this. Wildcard will do this, and admins should be using that instead of this.

**Comment by JeromSar** [comment]
@Wild1145 I don't want to block anything for admins unless absolutely necessary.

**Comment by Wild1145** [comment]
@JeromSar I think not blocking it will just lead to more confusing and inconstancies with admin training. Thats the reason after all that you removed a lot of the alieses for TFM commands and changed it so admins had to execute a set second parameter instead of the original long list.

**Comment by Nobody-11** [comment]
IF '**' is unblocked from admins, it would be unfair for ops, but we do have chat/wildcard admins won't be needed to use '**'

**Comment by zD12** [comment]
I must agree with @Nobody-11's and @Wild1145's statements.  If we did allow double-astrixes it will only confuse administrators during training.  @JeromSar, please reconsider your modification requests.

**Comment by JeromSar** [comment]
@StevenLawson what do you think?

**Comment by JeromSar** [comment]
@zD12 Upon reconsideration, I think you're right, merging soon.

**Comment by Wild1145** [comment]
@JeromSar Re-Open?

**Comment by Wild1145** [comment]
@JeromSar Bump

**Comment by Wild1145** [comment]
@JeromSar Another bump...

**Comment by DUFCLiam** [comment]
@JeromSar, Bump; Needs milestone.

**Comment by mayokek** [comment]
@DUFCLiam, this is made for TFM v4.3 not TFM v5.1

**Comment by DUFCLiam** [comment]
Oh yeah; I shall update this if I have time.

**Comment by Wild1145** [comment]
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

**Pull request closed without merging**
