### PR TITLE
Gj

### PR DESCRIPTION
**Pull request by Scuph**

### CODE REVIEW

**Comment by JeromSar** [comment]
Eh, no.

**Comment by Wild1145** [comment]
@JeromSar Why is it set out out in such a way for this command but not uniform with others?

**Comment by JeromSar** [comment]
@Wild1145 This line is particularly long, in contrast to other commands.

**Comment by Wild1145** [comment]
@JeromSar I mean the way that they are on separate lines, I dont believe the other commands are if I remember correctly.

**Pull request closed without merging**
