### PR TITLE
Change /nicknyan name length to 3

### PR DESCRIPTION
**Pull request by zD12**

### CODE REVIEW

**Comment by Wild1145** [comment]
@zD12 What's the purpose of the reduction from 4 to 3 characters?

**Comment by ncurran02** [comment]
You can have minimum of 3 characters in your name for Minecraft.

**Comment by PinkPanther1046** [comment]
I'm pretty sure I can fix this

**Comment by Wild1145** [comment]
Ahh that I did not realise. That's cool, I'll give it a once over when I get the CI working and we can merge it in assuming nothing obvious breaks (Which would be impressive)

**Pull request closed without merging**
