### PR TITLE
Create Command_compiletfm.java

### PR DESCRIPTION
**Pull request by ThePheonixBlader**
Add /compiletfm so people would know how to compile our mod instead of going around bugging people about: "How do I compile TotalFreedomMod? PLS HELP ME!!". It might need some minor adjustments, but I think it's good for now.

### CODE REVIEW

**Comment by AvalancheYT** [comment]
First, this PR doesn't meet the requirements (NO associated issue available)
Second, if they can't compile it. They shouldn't a developer at all.

**Comment by RobinGall2910** [comment]
taah, no, I think the TotalFreedomMod can't compile itself on a Minecraft server.

**Comment by AvalancheYT** [comment]
@RobinGall2910, you misunderstood, he meant like, when a person is coding TFM and wants to compile but can't. So they go in-game (TF) and do /compiletfm, it would show up how to compile it.

@JeromSar, It's a PR not an issue.

**Comment by ThePheonixBlader** [comment]
Yes, like Avalanche said, this is so if a person doesn't know how to compile TotalFreedomMod, they simply go on TF and do /compiletfm

**Comment by PacksGamingHD** [comment]
i think theres a guideline that says walls of text isn't allowed

**Comment by DUFCLiam** [comment]
Yes, @PacksGamingHD it is.

**Comment by RobinGall2910** [comment]
@AvalancheYT then this can't be accepted..

**Comment by Wild1145** [comment]
I might be mistaken, but originally at least the entire reason you had to compile TFM was because @StevenLawson wanted to ensure that you had sufficient knowledge to how TFM would actually affect your server before you install it with a load of other plugins and it all go to shit and you come back here complaining.

Now there are TFM releases in the releases tab, and they should be what most people really use, other versions of TFM are potentially part way through development, un-tested or unstable, its the entire point of the releases.

Oh, and the whole "Walls of text" commands are (I think) against the contributing guidelines.

**Pull request closed without merging**
