### PR TITLE
Cmdspy implement

### PR DESCRIPTION
**Pull request by ghost**
Allows higher to see inferior's rank cmds in-game.

thanks to MF dev @commodore

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Code needs to be formated to Allman Style

**Comment by ghost** [comment]
@ItzLevvie what do you mean?

**Comment by ghost** [comment]
@ItzLevvie i dont understand, the wikipedia thing, can you do it?

**Comment by ghost** [comment]
Locked, code bug

**Pull request closed without merging**
