### PR TITLE
/adminworld alias

### PR DESCRIPTION
**Pull request by CrafterSmith12**
Added:
/aw - alias for /adminworld

### CODE REVIEW

**Comment by DUFCLiam** [comment]
Denied, As it does not have an associated issue and is a one line commit

**Comment by Adaptified** [comment]
@DUFCLiam You. Have. No. Authority.

**Comment by Adamx120** [comment]
@DUFCLiam Can you not?????????????????

**Comment by Wild1145** [comment]
@Adaptified He is however correct.

**Comment by JeromSar** [comment]
Thanks for contributing!

This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements), and because of that, I cannot accept this issue.

**Pull request closed without merging**
