### PR TITLE
Improvements to the Maven Build Process & CI Intergration

### LINKED ISSUE #1888: Change Maven Library Process
Continued Discussion from [here](http://totalfreedom.boards.net/thread/46149/compiling-error?page=2).

Basically, it would be a lot easier for everyone involved if Maven does what Maven is supposed to do, as in get all of the dependencies remotely without relying on user-downloaded files.

Based off of the pom.xml file, this is simple to do. For Spigot I'm sure (I haven't done any MC development in ages, I might be wrong here) that you can just remove the directory link and it'll do it automatically - maybe not.

As for the rest of them, [JitPack](https://jitpack.io/) will handle the rest - I've used it in the dated [iTranxCraft plugin](https://github.com/TranxCraft/iTranxCraft/) without any problems.

This'll make development for newcomers easier as well as maintaining libraries easier for everyone else.

### PR DESCRIPTION
**Pull request by Wild1145**
This PR will allow for full automation on building of the TotalFreedomMod project, along with the ability to enable TravisCI Intergration that has been tested to be working. This PR resolves #1888 and part of #1948 however #1948 will also need to have TravisCI enabled at a repo level, something that I am unable to do anyway, however once it is enabled and this PR merged, all future PR's & Commits will be tested as part of the build process.

### CODE REVIEW

**Comment by ghost** [comment]
Looks good.

**Comment by Hockeyfan360** [comment]
@JeromSar You should really make this the number 1 priority, This would allow a lot more people to contribute to the project, taking some of the stress off of you. 

I've tried it and it works damn near flawlessly.

**Comment by Wild1145** [comment]
@Hockeyfan360 With the exception of the WorldEdit imports being funky, were there any other issues you had ran into? If so please do let me know and I will take a look into fixing said issues

**Review by lemonsked — DISMISSED** [review]
Looks good, I like it.

**Comment by JeromSar** [comment]
Looking into this as soon as I have time. :)

**Comment by Wild1145** [comment]
@JeromSar Currently the only issue with this is that The TF-LibsDisguise master branch doesnt compile... I will raise an issue there, but that blocks the merge of this one.

**Comment by Wild1145** [comment]
@JeromSar Just to update you, everything is now building as expected, @OxLemonxO has kindly fixed the issues with the TF-LibsDisguise repo that were causing failed builds.

**Review by JeromSar — CHANGES_REQUESTED** [review]
Getting this error:
`Failed to execute goal on project totalfreedom: Could not resolve dependencies for project me.totalfreedom:totalfreedom:jar:5.0: Could not find artifact com.github.TotalFreedom:TF-LibsDisguises:jar:-914c7289d5-1 in jitpack.io (https://jitpack.io) -> [Help 1]`

**Comment by Wild1145** [comment]
@JeromSar That is an upstream issue with the TF-LibsDisguise repo not currently being able to be built. There is an error of 

`[ERROR] Failed to execute goal on project LibsDisguises: Could not resolve dependencies for project LibsDisguises:LibsDisguises:jar:9.0.9: Could not find artifact org.spigotmc:spigot:jar:1.10-R0.1-SNAPSHOT in dmulloy2-repo (http://repo.dmulloy2.net/nexus/repository/public/) -> [Help 1]`

Its not an issue with this PR, but with the build ability of the branch its self.

**Comment by JeromSar** [comment]
@OxLemonxO Could you take a look, and see why TF-LibsDisguises is not building correctly?

**Comment by lemonsked** [comment]
@JeromSar It can't find  the 1.10 spigot jar, it needs both 1.11 and 1.10 jars for some reason.

**Comment by Wild1145** [comment]
One additional thing to note, the change to the README file will need to be adjusted once TravisCI integration is enabled within this repo, as it is currently referencing my fork and not this repo (I am not able to change that until after this PR and full TravisCI integration is up and running, short of removing the change all together).

**Comment by JeromSar** [comment]
@OxLemonxO Could you fix the issue, so this PR may be merged?

**Comment by Wild1145** [comment]
@JeromSar 1.12 binaries have now been built and an update has been pushed to the repo accordingly.

**Comment by JeromSar** [comment]
Will need a rebase/merge with `devel`. Could @OxLemonxO confirm that TF-LibsDisguises is building?

**Comment by lemonsked** [comment]
I've fixed the issue.

**Comment by mayokek** [comment]
It's not compiling - `Failed to execute goal on project totalfreedom: Could not resolve dependencies for project me.totalfreedom:totalfreedom:jar:5.0: Could not find artifact com.github.TotalFreedom:TF-LibsDisguises:jar:1.11.2-SNAPSHOT in ess-repo (http://repo.ess3.net)`

And also here - https://travis-ci.org/Wild1145/TotalFreedomMod/builds/241205241

**Review by JeromSar — APPROVED** [review]

**Comment by JeromSar** [comment]
Will need a merge/rebase.

**Comment by Wild1145** [comment]
I am still working on this, currently TF-LibsDisguise is not compiling, and as a result I havent been able to include it in this build. We need to look at other options long term. Though I do have some more tweaks for this PR yet.

**Comment by Wild1145** [comment]
@StevenLawson @JeromSar This is now building - I have had to drop support for TF-LibsDisguise and we will need to do some investigation as to if we can continue to support it.

**Review by JeromSar — CHANGES_REQUESTED** [review]
Can't get this to build anymore

Maybe these Maven logs will help:
https://pastebin.com/6bUz0ShF

**Comment by JeromSar** [comment]
@Wild1145 Any updates on this?

**Comment by Wild1145** [comment]
@JeromSar This combined with @StevenLawson's changes on one of the Maven branches to remove the need for Craftbukkit looks to be the way forward I think.

**Pull request merged**
