### PR TITLE
Add an announcement advertising the Mumble.

### PR DESCRIPTION
**Pull request by ImALuckyGuy**
The Mumble server is empty 99% of the time. Why not advertise it some?

### CODE REVIEW

**Comment by Wild1145** [comment]
Looks good to me.

**Comment by xDestroyer217** [comment]
@ImALuckyGuy :100: empty*

**Comment by ImALuckyGuy** [comment]
Actually, there were two people on it earlier today, which is why I put 99% instead of 100% :P

**Comment by xDestroyer217** [comment]
owo, randomm

**Comment by JeromSar** [comment]
@ImALuckyGuy Thanks for your contribution, merging soon.

**Comment by JeromSar** [comment]
Merged in https://github.com/TotalFreedom/TotalFreedomMod/commit/916fd75003972090e76a2eba4c5a3808d3044879

**Pull request closed without merging**
