### PR TITLE
Use proper server admin action name.

### PR DESCRIPTION
**Pull request by zD12**
Hi there, I do believe this should resolve issue #710

### CODE REVIEW

**Comment by Wild1145** [comment]
No.

**Comment by Scuph** [comment]
@Wild1145 Elaborate please? :P

**Comment by Wild1145** [comment]
@Scuph See the issue pertaining to this PR

**Comment by JeromSar** [comment]
@zD12 This shouldn't be RCOn, please set it to the Server's name, as defined in the config.

**Comment by JeromSar** [comment]
@zD12 About to close for inactivity, are you updating this?

**Comment by LegendIsAwesomes** [comment]
@JeromSar I'll be happy to create a new PR for this and other inactive PRS

**Pull request closed without merging**
