### PR TITLE
Update Command_gtfo.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
This is my PR.... can you stop copying others PRs.  @JeromSar what will happen since mine was closed due to a repo delete, I was gonna remake it.

**Comment by DUFCLiam** [comment]
I done it for you... @LegendIsAwesomes I would close if you made another one but Jerom just uses commits anyways does not merge them :P (Most of the time)

**Comment by LegendIsAwesomes** [comment]
Yes he does merge them , but not on the githuh website. I want this as my code not yours

**Comment by DUFCLiam** [comment]
Ok have you made the new PR?

**Comment by DUFCLiam** [comment]
Create the new PR and I will close this one.

**Comment by LegendIsAwesomes** [comment]
I cannot I am on mobile, just close this.

**Comment by DUFCLiam** [comment]
Wait, You can...

**Comment by DUFCLiam** [comment]
Click the part that says "Switch to Desktop version" and then that is good!

**Comment by Wild1145** [comment]
Can you all stop bitching please...

1) Do not delete branches
2) Do not copy code
3) play nice or get off this github, its not for bitching.

**Pull request closed without merging**
