### PR TITLE
Blocking muted from using alternate speaking commands.

### PR DESCRIPTION
**Pull request by LegendIsAwesomes**
https://github.com/TotalFreedom/TotalFreedomMod/issues/716

Just blocks them from doing the commands mentioned in the issue.

I think this is correct. Not too sure.

### CODE REVIEW

**Comment by Wild1145** [comment]
Would have been more sensible to either add them all at the end of the list or add the alternate commands next to the current ones personally.

**Comment by Adaptified** [comment]
Might as well remove say, because it's admin only.

**Comment by looperXD** [comment]
May you add /action? It works same as /me

**Comment by LegendIsAwesomes** [comment]
Added /action. @JeromSar

**Comment by JeromSar** [comment]
@LegendIsAwesomes This is good, but needs a different implementation. Instead of blocking all the aliases, please change it to automatically block all aliases by resolving each command name to its associated `Command` instance. That way, aliases are automatically blocked.

**Pull request closed without merging**
