### PR TITLE
Resolves #974 - Add "/trail glass" function to command "/trail"

### LINKED ISSUE #974: /glasstrail
/glasstrail - I  suggest to add that, I know its pointless, but funny. 

Its the same as /trail, but with stained_glass!

### PR DESCRIPTION
**Pull request by ghost**
Some changes:
Command "/trail off"
- Disabled GlassTrail and Trail too.
  Command /trail
  When you use trail, you can force switch from /trail to /trail glass
  and from /trail glass to /trail

Known Issues:
 If you use "/trail glass" 2 times or more 
You need to use "/trail off" too 2 times
Because:
If you use /trail glass it adds you to the glasstrail list, and if you use it multiple times it adds you like when you use it twice :
List in the program:
- Adamx120
- Adamx120

And /trail off, removes you ONCE from this list, so you keep with the trail and you need to use off again

### CODE REVIEW

**Comment by DarkGamingDronze** [comment]
I was gonna make a pull request about this. I am happy that you brought this up.

**Review by Wild1145 — COMMENTED** [review]
Requires testing.

**Review by Wild1145 — CHANGES_REQUESTED** [review]
Merge conflicts.

**Comment by Wild1145** [comment]
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.

**Pull request closed without merging**
