### PR TITLE
Added Admin Name in smite

### PR DESCRIPTION
**Pull request by marcocorriero**
Added Admin Name in smite

Smite will say who smite ops, sorry for wrong pull.

### CODE REVIEW

**Comment by Wild1145** [comment]
What issue does this resolve?

**Comment by marcocorriero** [comment]
#1776 @Wild1145

**Comment by Wild1145** [comment]
Excellent, looks good to me.

**Comment by OxLemonxO** [comment]
This does not meet the Contributing Guidelines:
PRs must not solely be grammar fixes, config-edits, **small changes (less than 10 lines of code) or message rephrasing edits.** Small edits such as these take very little effort to make and a lot more effort to review and integrate into the codebase.

**Comment by PacksGamingHD** [comment]
btw this doesn't compile for me

**Comment by JeromSar** [comment]
Thanks for contributing!

This pull request does not meet the [pull request requirements](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing#pull-request-requirements), and because of that, I cannot accept this issue.

**Pull request closed without merging**
