### PR TITLE
Commodore64x   #1979 glist upgrade

### PR DESCRIPTION
**Pull request by ghost**
Code for #1979

### CODE REVIEW

**Comment by ghost** [comment]
@Wild1145 is broken, it doesn't work correctly.

Ban is messed up!
banip doesn't ban.

**Comment by ghost** [comment]
@Wild1145 @Commodore64x i made a working glist ipban/ripban/ban and unbanip/runbanip/unban, just need formatting. idk how.

**Comment by ghost** [comment]
Stop spamming all the issues and PRs saying how things do not work, I have tested them myself and they work fine. I will modify the regex to include the character *

**Comment by ghost** [comment]
@Commodore64x it bans with ban, and bans it doesn't respect the original one. here why is not working.
btw come to discord, ill show my edit

**Comment by ghost** [comment]
Tested, working great

**Comment by robingall2910** [comment]
I recommend you to just put all of these commits into one instead of making like 30 of them for one PR.

**Comment by Wild1145** [comment]
@robingall2910 They can be squashed anyway for when its merged. Multiple commits right now isnt a bad thing, as it allows us to see what has happend between changes.

**Comment by robingall2910** [comment]
@Wild1145 if that can be squashed, then never mind about what I said lol

**Comment by Wild1145** [comment]
Due to the original repo being removed it appears, I am closing down this PR.

**Pull request closed without merging**
