### PR TITLE
Block /green - Resolve #594

### LINKED ISSUE #594: /green
I have no idea what it should be used for but, players use /green 9001 and it crashes the server when they use it. This either needs to be blocked or edited .

### PR DESCRIPTION
**Pull request by SlicedCaek**

### CODE REVIEW

**Comment by Wild1145** [comment]
What does /green even do?

**Comment by AlexFreedomMod** [comment]
@Wild1145  it makes the dirt in the area grass.

**Comment by Scuph** [comment]
@Wild1145 Which in further explanation

/green 9001 makes the nearest 9,001 dirt blocks green in one instance, overloading the server.

**Comment by AlexFreedomMod** [comment]
@Scuph is right.

**Comment by JeromSar** [comment]
@DaBoyTM Thanks for your contribution. This PR will be merged soon. Hang tight. :)

**Comment by xDestroyer217** [comment]
Damn, he beat me to it.

**Comment by JeromSar** [comment]
Merged in https://github.com/TotalFreedom/TotalFreedomMod/commit/abf52870dd8ac13522cd4122a58e3a6c1d17a43c

**Pull request closed without merging**
