### PR TITLE
Commodore64x #1830 /cmdspy

### PR DESCRIPTION
**Pull request by ghost**
Code for #1980

### CODE REVIEW

**Review by Wild1145 — CHANGES_REQUESTED** [review]
I would probably re-structure this to first check if command spy is enabled, and then what the rank is, its just more structured instead of having if statement after if statement.

**Comment by Wild1145** [comment]
Please also update the description to reflect the new issue number.

**Comment by ghost** [comment]
@Wild1145 please elaborate on what you want me to change.

**Comment by Wild1145** [comment]
@Commodore64x You should be checking if the user has command spy enabled first, then doing additional checks after. Also you should have a reference to the new issue (the one your issue was superseded by) in the opening message of this PR.

**Comment by Wild1145** [comment]
Due to the original repo having been destroyed, I am closing this PR down as a result.

**Pull request closed without merging**
