### PR TITLE
Just like Cake but gives you COOKIES!!

### PR DESCRIPTION
**Pull request by AlphaGaming**

### CODE REVIEW

**Comment by PacksGamingHD** [comment]
not needed

**Comment by JeromSar** [comment]
This is basically /cake, copied. If you're planning to create a fun command, it needs to be original. For this reason, I'm closing this PR.

**Comment by Wild1145** [comment]
I am 99% sure we did have /cookie at one point... Unless it was when TF was running CJFM and I am getting confused...

**Comment by JeromSar** [comment]
@Wild1145 Yes we did, it was removed for this reason.

**Pull request closed without merging**
