### PR TITLE
Let's non-ops do /opme

### PR DESCRIPTION
**Pull request by savnithyt**
Look at: https://github.com/TotalFreedom/TotalFreedomMod/issues/2082

### CODE REVIEW

**Comment by falceso** [comment]
Honestly I think someone rejected something like this for if someone gets smite they reop themselves instantly etc.

**Comment by aggelosQQ** [comment]
I'll agree to this if there is something that will prevent recently smitten players or users that are marked as imposters from opping themselves.

**Comment by ghost** [comment]
Same as I said on the issue: This has been denied in various suggestions on the forums, it is unlikely to be added. There are no checks for ops that have been smitten/purposefully deopped.

**Review by LiamTownsley — APPROVED** [review]
I agree with this. Mainly because if they should not have OP they should not be on the server and should be banned.

**Comment by Wild1145** [comment]
Thank you for contributing to the project. Please read the [Contributing Guidelines](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing) carefully before contributing to the project in the future!

**Pull request closed without merging**
