### PR TITLE
Block /rl as a normal blocked command. Resolves #525

### LINKED ISSUE #525: Make /rl as a normal blocked command
Mark told me to suggest that here, also, I do agree doing this because, too much pepole tell other pepole to do /rl for rocketlauncher.... and it bans innocent pepole. Can we just keep it as a normal blocked command?

PR: #526

### PR DESCRIPTION
**Pull request by xDestroyer217**
Commit for #525

### CODE REVIEW

**Comment by AlexFreedomMod** [comment]
Nice

**Comment by xDestroyer217** [comment]
Worked in my side..

**Comment by JeromSar** [comment]
@xDestroyer217 Thanks for your contribution, it'll be merged soon. :)

**Comment by JeromSar** [comment]
Merged in https://github.com/TotalFreedom/TotalFreedomMod/commit/53efcfd06b0a9a036dfd68a68e20983a09667dee

**Pull request closed without merging**
